/**
 * APP_STRINGS — single source of truth for every UI string in the BookEase web app.
 * Organised by screen / feature. Import and reference instead of inline literals.
 *
 * Usage:
 *   import { APP_STRINGS } from '../../../core/constants';
 *   readonly S = APP_STRINGS;   // alias in component class
 *   {{ S.AUTH.LOGIN_BUTTON }}   // in template
 */

export const APP_STRINGS = {

  // ─── Brand ─────────────────────────────────────────────────────────────────
  BRAND: {
    NAME: 'BookEase',
    TAGLINE: 'Train with the best. Book in seconds.',
    FOOTER_COPYRIGHT: '© 2026 BookEase Inc.',
    FOOTER_LINKS: ['Services', 'Pricing', 'About', 'Contact', 'Privacy'],
  },

  // ─── Navigation ────────────────────────────────────────────────────────────
  NAV: {
    SERVICES: 'Services',
    HOW_IT_WORKS: 'How it works',
    PRICING: 'Pricing',
    CONTACT: 'Contact',
    LOG_IN: 'Log in',
    BOOK_NOW: 'Book Now',
    BOOK_SESSION: 'Book a session',
    ADMIN: 'Admin',
    VIEW_SITE: 'View site',
    MY_BOOKINGS: 'My bookings',
    HELP: 'Help',
  },

  // ─── Common / Shared ────────────────────────────────────────────────────────
  COMMON: {
    BOOK: 'Book',
    CANCEL: 'Cancel',
    SAVE: 'Save',
    EDIT: 'Edit',
    REMOVE: 'Remove',
    CONFIRM: 'Confirm',
    BACK: 'Back',
    OR: 'OR',
    LOADING: 'Loading…',
    SAVING: 'Saving…',
    OPTIONAL: '(optional)',
    VIEW_ALL: 'View all →',
    SORT_POPULAR: 'Sort: Popular',
    FREE_CANCELLATION: 'Free cancellation up to 12h before',
    MIN_SUFFIX: 'min',
    SESSION_SUFFIX: '/ session',
    PER_MONTH: '/mo',
  },

  // ─── Home / Landing ────────────────────────────────────────────────────────
  HOME: {
    HERO_BADGE: 'Personal training, on your schedule',
    HERO_TITLE: 'Train with the best.\nBook in seconds.',
    HERO_SUBTITLE: 'Find a coach, pick a time that fits your week, and lock in your session — no calls, no back-and-forth.',
    HERO_CTA_PRIMARY: 'Book Now',
    HERO_CTA_SECONDARY: 'View Services',
    RATING_TEXT: '★★★★★ 4.9',
    RATING_SUBTEXT: '2,400+ sessions booked',
    SESSION_CONFIRMED: 'Session confirmed',
    SESSION_COACH: '10:30 AM · Coach Mia',
    SERVICES_EYEBROW: 'SERVICES',
    SERVICES_HEADING: 'Popular services',
    HOW_EYEBROW: 'HOW IT WORKS',
    HOW_HEADING: 'Booked in three steps',
    WHY_EYEBROW: 'WHY BOOKEASE',
    WHY_HEADING: 'Everything in one place',
    TESTIMONIALS_EYEBROW: 'TESTIMONIALS',
    TESTIMONIALS_HEADING: 'Loved by clients & coaches',
    TESTIMONIAL_1_BODY: '"I booked three sessions in under a minute. BookEase made finding a coach genuinely effortless."',
    TESTIMONIAL_1_NAME: 'Jordan Hayes',
    TESTIMONIAL_1_SINCE: 'Member since 2025',
    TESTIMONIAL_2_BODY: '"As a trainer, the admin dashboard saves me hours every week. My calendar finally runs itself."',
    TESTIMONIAL_2_NAME: 'Coach Mia Reyes',
    TESTIMONIAL_2_ROLE: 'Strength specialist',
    PACKAGES_EYEBROW: 'PACKAGES',
    PACKAGES_HEADING: 'Simple, fair pricing',
    CTA_HEADING: 'Ready to start training?',
    CTA_SUBTEXT: 'Join thousands booking smarter with BookEase.',
    CTA_BUTTON: 'Book your first session',

    STEPS: [
      { title: 'Choose a service', desc: 'Browse coaches and programs, filter by what you need.' },
      { title: 'Pick a time slot', desc: 'See live availability and select the slot that fits.' },
      { title: 'Confirm & go',     desc: 'Get instant confirmation and a calendar invite.' },
    ] as const,

    FEATURES: [
      { icon: '⚡', title: 'Instant booking',      desc: 'Real-time availability, no waiting on a callback.' },
      { icon: '✅', title: 'Verified coaches',     desc: 'Every trainer is certified and client-reviewed.' },
      { icon: '📅', title: 'Flexible reschedule',  desc: 'Move or cancel up to 12 hours before, free.' },
      { icon: '💳', title: 'Secure payments',      desc: 'Pay safely in-app with saved cards or Apple Pay.' },
    ] as const,
  },

  // ─── Services ──────────────────────────────────────────────────────────────
  SERVICES: {
    PAGE_EYEBROW: '24 services across 6 categories',
    PAGE_HEADING: 'Find the training that fits you',
    PAGE_SUBTEXT: 'From 1:1 strength coaching to mobility and nutrition — every session is led by a verified coach and bookable in seconds.',
    BROWSE_HEADING: 'Browse services',
    FILTER_ALL: 'All',
    SEARCH_PLACEHOLDER: 'Search services or coaches…',
    EMPTY_TITLE: 'No services found',
    EMPTY_MESSAGE: 'Try adjusting your search or category filter.',
    NO_SLOTS: 'No slots available for this date.',
    WHATS_INCLUDED: "What's included",
    BOOK_SESSION_PANEL_TITLE: 'Book this session',
    SELECT_TIME: 'Select a time slot',
    CHOOSE_DATE_LABEL: 'Choose a date',
    SELECT_TIME_LABEL: 'Select time',
    CTA_HEADING: 'Not sure where to start?',
    CTA_SUBTEXT: 'Book a free fitness assessment and we\'ll match you to a coach.',
    CTA_BUTTON: 'Book assessment',
    BACK_TO_SERVICES: '← Back to services',
  },

  // ─── Booking ───────────────────────────────────────────────────────────────
  BOOKING: {
    PAGE_TITLE: 'Book your session',
    STEP_SERVICE: 'Service',
    STEP_DETAILS: 'Details',
    STEP_CONFIRM: 'Confirm',
    SELECT_DATE: 'Select a date',
    AVAILABLE_SLOTS: 'Available time slots',
    YOUR_DETAILS: 'Your details',
    LABEL_FULL_NAME: 'Full name',
    LABEL_PHONE: 'Phone',
    LABEL_EMAIL: 'Email',
    LABEL_NOTES: 'Notes',
    PLACEHOLDER_FULL_NAME: 'Jordan Hayes',
    PLACEHOLDER_PHONE: '+1 415 555 0199',
    PLACEHOLDER_EMAIL: 'jordan@email.com',
    PLACEHOLDER_NOTES: 'Recovering from a minor knee strain — please keep impact low.',
    SUMMARY_TITLE: 'Booking summary',
    SUMMARY_WITH: 'with',
    SUMMARY_DATE: 'Date',
    SUMMARY_TIME: 'Time',
    SUMMARY_DURATION: 'Duration',
    SUMMARY_TOTAL: 'Total',
    CONFIRM_BUTTON: 'Confirm booking',
    CONFIRMING_BUTTON: 'Confirming…',
    ERROR_SELECT_SLOT: 'Please select an available time slot.',
    ERROR_REQUIRED: 'This field is required.',
    TOAST_MISSING: 'Please select a time slot and fill in your details.',
    TOAST_CONFIRMED: 'Booking confirmed! Check your email for details.',
    TOAST_ERROR: 'Something went wrong. Please try again.',
  },

  // ─── Confirmation ──────────────────────────────────────────────────────────
  CONFIRMATION: {
    HEADING: 'Booking confirmed!',
    SUBTEXT_PREFIX: "We've sent the details and a calendar invite to",
    SUBTEXT_FALLBACK: 'your email',
    LABEL_BOOKING_ID: 'Booking ID',
    LABEL_SERVICE: 'Service',
    LABEL_DATE_TIME: 'Date & time',
    LABEL_COACH: 'Coach',
    LABEL_CUSTOMER: 'Customer',
    BACK_TO_HOME: 'Back to Home',
    VIEW_BOOKINGS: 'View Bookings',
    LOADING: 'Loading booking details…',
  },

  // ─── Auth / Login ──────────────────────────────────────────────────────────
  AUTH: {
    BRAND_HEADLINE: 'Your next session is\none tap away.',
    BRAND_SUBTEXT: 'Verified coaches, real-time availability, and seamless bookings — all in one place.',
    TESTIMONIAL_BODY: '"Booking finally feels effortless."',
    TESTIMONIAL_AUTHOR: 'Jordan H.',
    TESTIMONIAL_SINCE: 'Member since 2025',
    WELCOME_HEADING: 'Welcome back',
    WELCOME_SUBTEXT: 'Log in to your BookEase account.',
    LABEL_EMAIL: 'Email',
    PLACEHOLDER_EMAIL: 'your@email.com',
    LABEL_PASSWORD: 'Password',
    FORGOT_PASSWORD: 'Forgot?',
    REMEMBER_ME: 'Keep me logged in',
    LOGIN_BUTTON: 'Log in',
    TOGGLE_PASSWORD_ARIA: 'Toggle password visibility',
    OR_DIVIDER: 'OR',
    GOOGLE_BUTTON: 'Google',
    APPLE_BUTTON: 'Apple',
    NO_ACCOUNT: "Don't have an account?",
    SIGN_UP_LINK: 'Sign up',
    ERROR_EMAIL: 'Enter a valid email address.',
    ERROR_PASSWORD: 'Password must be at least 8 characters.',
    TOAST_WELCOME: 'Welcome back!',
    TOAST_CHECK_CREDENTIALS: 'Please check your email and password.',
    PROOF_POINTS: [
      '2,400+ sessions booked this month',
      'Verified, client-reviewed coaches',
      'Free rescheduling, anytime',
    ] as const,
  },

  // ─── How it Works ──────────────────────────────────────────────────────────
  HOW_IT_WORKS: {
    EYEBROW: 'HOW IT WORKS',
    HEADING: 'Booked in three simple steps',
    SUBTEXT: 'No phone calls, no waiting on replies. Go from browsing to a confirmed session in under a minute.',
    GUARANTEE_INSTANT_TITLE: 'Instant confirmation',
    GUARANTEE_INSTANT_DESC: 'Slots update live — what you see is what you get.',
    GUARANTEE_RESCHEDULE_TITLE: 'Free rescheduling',
    GUARANTEE_RESCHEDULE_DESC: 'Plans change. Move or cancel up to 12 hours before.',
    GUARANTEE_PAYMENTS_TITLE: 'Secure payments',
    GUARANTEE_PAYMENTS_DESC: 'Pay safely with saved cards or Apple Pay.',

    STEPS: [
      {
        title: 'Choose a service',
        description: 'Browse coaches and programs, filter by goal, schedule and budget. Every coach is verified and client-reviewed.',
      },
      {
        title: 'Pick a time slot',
        description: 'See real-time availability and lock the slot that fits your week. Reschedule free up to 12 hours before.',
      },
      {
        title: 'Confirm & go',
        description: 'Pay securely in-app and get instant confirmation plus a calendar invite. Just show up and train.',
      },
    ] as const,
  },

  // ─── Pricing ───────────────────────────────────────────────────────────────
  PRICING: {
    EYEBROW: 'PRICING',
    HEADING: 'Simple, fair pricing',
    SUBTEXT: 'Start free and pay per session, or save with a monthly plan. Cancel anytime.',
    BILLING_MONTHLY: 'Monthly',
    BILLING_YEARLY: 'Yearly · save 20%',
    BADGE_POPULAR: 'MOST POPULAR',
    PLAN_STARTER_NAME: 'Starter',
    PLAN_STARTER_PRICE: '$0',
    PLAN_STARTER_BILLING: 'Pay per session',
    PLAN_STARTER_FEATURES: ['✓ Book any service', '✓ Reminders & calendar sync', '✓ In-app payments'] as const,
    PLAN_STARTER_CTA: 'Get started',
    PLAN_PRO_NAME: 'Pro',
    PLAN_PRO_BILLING: '8 sessions / month',
    PLAN_PRO_FEATURES: ['✓ Everything in Starter', '✓ Priority slots', '✓ Free rescheduling', '✓ Progress tracking'] as const,
    PLAN_PRO_CTA: 'Choose Pro',
    PLAN_ELITE_NAME: 'Elite',
    PLAN_ELITE_BILLING: 'Unlimited sessions',
    PLAN_ELITE_FEATURES: ['✓ Everything in Pro', '✓ Dedicated coach', '✓ Custom nutrition plan'] as const,
    PLAN_ELITE_CTA: 'Choose Elite',
    FAQ_HEADING: 'Pricing questions',
    FAQS: [
      'Can I switch plans later?',
      'Do unused sessions roll over?',
      'Is there a cancellation fee?',
    ] as const,
  },

  // ─── Contact ───────────────────────────────────────────────────────────────
  CONTACT: {
    EYEBROW: 'GET IN TOUCH',
    HEADING: "We'd love to hear from you",
    SUBTEXT: 'Questions about a service, your booking, or partnering as a coach? Send us a note and we\'ll reply within a day.',
    LABEL_FIRST_NAME: 'First name',
    LABEL_LAST_NAME: 'Last name',
    LABEL_EMAIL: 'Email',
    LABEL_TOPIC: 'Topic',
    LABEL_MESSAGE: 'Message',
    TOPIC_PLACEHOLDER: 'Select a topic',
    TOPIC_BOOKING: 'Booking help',
    TOPIC_COACH: 'Partner as a coach',
    TOPIC_BILLING: 'Billing question',
    TOPIC_OTHER: 'Other',
    PLACEHOLDER_MESSAGE: 'Tell us a bit about what you need…',
    SUBMIT_BUTTON: 'Send message',
    CONTACT_EMAIL_LABEL: 'Email us',
    CONTACT_EMAIL_VALUE: 'hello@bookease.app',
    CONTACT_PHONE_LABEL: 'Call us',
    CONTACT_PHONE_VALUE: '+1 (415) 555-0100',
    CONTACT_LOCATION_LABEL: 'Visit the studio',
    CONTACT_LOCATION_VALUE: '540 Market St, San Francisco',
    HOURS_TITLE: 'Opening hours',
    HOURS_WEEKDAYS_LABEL: 'Mon – Fri',
    HOURS_WEEKDAYS_VALUE: '6:00 AM – 9:00 PM',
    HOURS_SATURDAY_LABEL: 'Saturday',
    HOURS_SATURDAY_VALUE: '8:00 AM – 6:00 PM',
    HOURS_SUNDAY_LABEL: 'Sunday',
    HOURS_SUNDAY_VALUE: 'Closed',
    MAP_PLACEHOLDER: 'Map / studio photo',
    TOAST_SUCCESS: "Message sent! We'll be in touch within a day.",
    TOAST_ERROR: 'Please fill in all required fields.',
    ERROR_REQUIRED: 'This field is required.',
    ERROR_MIN_LENGTH_NAME: 'Must be at least 2 characters.',
    ERROR_MIN_LENGTH_MESSAGE: 'Message must be at least 10 characters.',
    ERROR_EMAIL: 'Enter a valid email address.',
  },

  // ─── Admin ─────────────────────────────────────────────────────────────────
  ADMIN: {
    SIDEBAR_TAG: 'Admin',
    NAV_DASHBOARD: 'Dashboard',
    NAV_BOOKINGS: 'Bookings',
    NAV_SERVICES: 'Services',

    // Dashboard
    DASHBOARD_TITLE: 'Dashboard',
    NEW_BOOKING_CTA: '+ New booking',
    KPI_TOTAL_BOOKINGS: 'Total bookings',
    KPI_REVENUE: 'Revenue',
    KPI_CUSTOMERS: 'Customers',
    KPI_ACTIVE_SERVICES: 'Active services',
    RECENT_BOOKINGS_TITLE: 'Recent bookings',
    RECENT_BOOKINGS_LINK: 'View all →',
    TABLE_COL_REF: 'Ref',
    TABLE_COL_CUSTOMER: 'Customer',
    TABLE_COL_SERVICE: 'Service',
    TABLE_COL_DATE: 'Date',
    TABLE_COL_AMOUNT: 'Amount',
    TABLE_COL_STATUS: 'Status',
    WEEKLY_BOOKINGS_TITLE: 'Weekly bookings',

    // Bookings management
    BOOKINGS_TITLE: 'Bookings',
    SEARCH_PLACEHOLDER: 'Search ref or customer…',
    FILTER_ALL_STATUSES: 'All statuses',
    FILTER_PENDING: 'Pending',
    FILTER_CONFIRMED: 'Confirmed',
    FILTER_COMPLETED: 'Completed',
    FILTER_CANCELLED: 'Cancelled',
    TABLE_COL_COACH: 'Coach',
    TABLE_COL_DATE_TIME: 'Date & time',
    TABLE_COL_ACTIONS: 'Actions',
    ACTION_CONFIRM: 'Confirm',
    ACTION_CANCEL: 'Cancel',
    ACTION_COMPLETE: 'Complete',
    SHOWING_COUNT_PREFIX: 'Showing',
    SHOWING_COUNT_OF: 'of',
    SHOWING_COUNT_SUFFIX: 'bookings',
    EMPTY_BOOKINGS_TITLE: 'No bookings found',
    EMPTY_BOOKINGS_MESSAGE: 'Try adjusting your search or status filter.',

    // Services management
    SERVICES_TITLE: 'Services',
    ADD_SERVICE_BUTTON: '+ Add service',
    TABLE_COL_CATEGORY: 'Category',
    TABLE_COL_DURATION: 'Duration',
    TABLE_COL_PRICE: 'Price',
    TABLE_COL_RATING: 'Rating',
    TABLE_COL_SERVICE_STATUS: 'Status',
    ACTION_EDIT: 'Edit',
    ACTION_REMOVE: 'Remove',
    SERVICE_ACTIVE: 'Active',
    SERVICE_INACTIVE: 'Inactive',
    FORM_ADD_TITLE: 'Add service',
    FORM_EDIT_TITLE: 'Edit service',
    FORM_LABEL_NAME: 'Name *',
    FORM_LABEL_DESCRIPTION: 'Description',
    FORM_LABEL_PRICE: 'Price (cents) *',
    FORM_LABEL_DURATION: 'Duration (min) *',
    FORM_LABEL_CATEGORY: 'Category',
    FORM_LABEL_COACH: 'Coach name',
    FORM_LABEL_IMAGE_URL: 'Image URL',
    FORM_PLACEHOLDER_NAME: 'e.g. Power Strength',
    FORM_PLACEHOLDER_PRICE: '6500',
    FORM_PLACEHOLDER_DURATION: '60',
    FORM_PLACEHOLDER_COACH: 'Marcus Reid',
    FORM_PLACEHOLDER_IMAGE: 'https://…',
    FORM_CATEGORY_PLACEHOLDER: 'Select…',
    FORM_CANCEL: 'Cancel',
    FORM_SAVE_ADD: 'Add service',
    FORM_SAVE_UPDATE: 'Update',
    DELETE_DIALOG_TITLE: 'Remove service?',
    DELETE_DIALOG_DESC: 'This will deactivate the service and hide it from bookings.',
    DELETE_DIALOG_CONFIRM: 'Remove',
    EMPTY_SERVICES_TITLE: 'No services yet',
    EMPTY_SERVICES_MESSAGE: 'Add your first service using the button above.',
  },

  // ─── Errors ────────────────────────────────────────────────────────────────
  ERRORS: {
    REQUIRED: 'This field is required.',
    EMAIL_INVALID: 'Enter a valid email address.',
    PASSWORD_TOO_SHORT: 'Password must be at least 8 characters.',
    MIN_LENGTH_2: 'Must be at least 2 characters.',
    MIN_LENGTH_10: 'Message must be at least 10 characters.',
    GENERIC: 'Something went wrong. Please try again.',
    NO_RESULTS_TITLE: 'Nothing here yet',
    NO_RESULTS_MESSAGE: 'Try adjusting your filters.',
  },

} as const;

export type AppStrings = typeof APP_STRINGS;
